#!/bin/bash
set -e

# Create the Grafana user and database, and set the user as the owner.
psql -v ON_ERROR_STOP=1 --username "$POSTGRES_USER" --dbname "$POSTGRES_DB" <<-EOSQL
    CREATE USER $GRAFANA_USER WITH PASSWORD '$GRAFANA_PASSWORD';
    CREATE DATABASE $GRAFANA_DB OWNER $GRAFANA_USER;

    CREATE USER $OPENWEBUI_USER WITH PASSWORD '$OPENWEBUI_PASSWORD';
    CREATE DATABASE $OPENWEBUI_DB OWNER $OPENWEBUI_USER;
EOSQL